version: 0.2

phases:
  install:
    commands:
      - yarn install
  pre_build:
    commands:
      - echo Pre-build phase complete
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - "**/*"
  base-directory: build

cache:
  paths:
    - node_modules/**/*
